# Generated by Django 5.0.1 on 2024-01-30 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mediuns',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('atuante_no_grupo', models.CharField(choices=[('S', 'SIM'), ('N', 'NÃO')], default='N', max_length=1)),
                ('participa_estudo_evangelho', models.CharField(choices=[('S', 'SIM'), ('N', 'NÃO')], default='N', max_length=1)),
            ],
        ),
    ]
