# Generated by Django 5.0.1 on 2024-01-31 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediuns',
            name='celphone',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
