# Generated by Django 5.0.1 on 2024-01-30 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enviapedidoprece', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoprece',
            name='participa_estudo_evangelho',
            field=models.CharField(choices=[('S', 'SIM'), ('N', 'NÃO')], default='N', max_length=1),
        ),
    ]
