# Generated by Django 5.0.1 on 2024-01-30 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enviapedidoprece', '0002_pedidoprece_participa_estudo_evangelho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidoprece',
            name='acolhido_encarnado',
            field=models.CharField(choices=[('S', 'Encarnado'), ('N', 'Desencarnado')], default='S', max_length=1),
        ),
    ]
