# Generated by Django 5.0.1 on 2024-01-30 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enviapedidoprece', '0003_alter_pedidoprece_acolhido_encarnado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidoprece',
            name='participa_estudo_evangelho',
        ),
    ]
